### ISSUE TITLE
Initial conditions for COAWST

### ISSUE THREAD

**Issue by ben108472** [DOI-USGS/COAWST#14]
I have read the user manual for COAWST, but the source for initail condition(such as tidal data) is not clear in it.
Is there any full description for processing initail condition for COAWST(except WRF).

**Comment by mf99274** [comment]
Hi ben108472, 

I use TPXO9 for tides (https://www.tpxo.net/global/tpxo9-atlas), and using HYCOM for forcing ROMS (look for https://www.myroms.org/forum/) which is the ocean part. Like they said it to me in the beginning, start small, try to learn ROMS and how it works by running their test cases and then move on to the coupling phase (I am in this part now). 

Cheers and good luck,

**Comment by jcwarner-usgs** [comment]
i am not clear what you mean by initial tidal data.  Do you mean the initial water levels for the model, or do you mean the tidal forcing on the open boundary?

**Comment by ben108472** [comment]
> i am not clear what you mean by initial tidal data. Do you mean the initial water levels for the model, or do you mean the tidal forcing on the open boundary?

The user manual says tidal forcing and surface forcings are needed for ROMS to run.
However, I don't know where to download these files in different ocean basin(such as western pacific ocean or indian ocean).

**Comment by mf99274** [comment]
People use the tidal data either from adcirc or the website I posted here (you can get by basins or entire globe I normally get the entire globe). For surface forcing if you mean atmospheric data there's this website https://rda.ucar.edu/#!lfd?nb=y&b=plat&v=REANALYSIS%20MODELS where you can get the atmospheric forcing for the entire globe. If you are talking about u,v, salt,temp, and ssh you can get from HYCOM (https://www.hycom.org/), SODA(http://www.soda.umd.edu/), or from Copernicus (https://resources.marine.copernicus.eu/?option=com_csw&task=results). 

There are several tools available. Once you download COAWST, there's a folder called **Tools** where after downloading your data you can use to create your files for forcing ROMS (check the tools to see if the dataset you wanna use is being used in the matlab files otherwise you will have to tweak the matlab files in order to use the data you wanna use). If you are a python user, there are several python packages you can use to create your forcings except Tides, I haven't found a good one and as good as  the tides codes in matlab like the one found in the **Tools** folder yet.  I am a python user but when I started using ROMS I used the matlab codes because they are easy to understand and super documented but over the years I have been transitioning my codes to python so nowadays the only codes I use in matlab are the tides codes. 


I don't know how much more helpful I can be. Again... go to ROMS forum https://www.myroms.org/forum/index.php?sid=58ba98cfc1429485f94ff5e3f4c6bf4c and there you can find all sorts of helps and questions similar to yours with good answers, the community is super helpful too!!!

Cheers,
Matheus

**Comment by ben108472** [comment]
@mf99274 
Thank you for your reply.
If I want to run a real tropical cyclones case in WRF+ROMS, should I need to process the tidal forcing and surface forcing data?
WRF model can provide surface forcing. Why should I have to provide surface forcing?
P.S. ROMS forum is not open for registration.

**Comment by mf99274** [comment]
Hey, 

So I don't run tropical cyclones but the one time I did experiment with that was during the COAWST workshop. And you are right you don't need surface forcing from atmospheric data if you are using WRF. 

Cheers,

P.S: it is super tedious in the beginning but don't give up. :)
