### ISSUE TITLE
module_ra_rrtm.f90 error when coupling SWAN+WRF

### ISSUE THREAD

**Issue by mf99274** [DOI-USGS/COAWST#15]
Hi John (again), 

I am having trouble to run SWAN+WRF after building it properly and probably is something really silly but I can't see/figure it out. Thus, I was wondering if you have had this problem before (see build_swan+wrf.txt in the zip file attached). As you can see when running WRF by itself or SWAN by itself they both run with no problem (wrfOut.txt and CCS_hsig.nc, respectively) so I am assuming my input/grid data for both models are right, so maybe I am not setting the proper flags in the swan+wrf.h file? Also, the error is WRF related and the closest answer that I got was from this link (https://www.researchgate.net/post/I_am_unable_to_figure_out_the_error_FATAL_CALLED_FROM_FILE_set_timekeepingG_after_execution_of_realexe_file_in_WRF) which is related to WRF only. 

[outputCoawst.zip](https://github.com/jcwarner-usgs/COAWST/files/5250410/outputCoawst.zip)

Thank you in advance,
Matheus

**Comment by jcwarner-usgs** [comment]
i have seen this before.

Edit the file Compilers/Linux-gfortran.mk and change lines 183 and 184 from

           FFLAGS += -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4

##                   -fconvert=big-endian

to

           FFLAGS += -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4  -fconvert=big-endian

you will need to do a full recompile.
let me know if that works.  That big-endian flag is in the wrf build already, you can search the file you sent and see it is in there.


-j


John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
jcwarner@usgs.gov<mailto:jcwarner@usgs.gov>

https://www.usgs.gov/staff-profiles/john-warner


________________________________

**Comment by jcwarner-usgs** [comment]
yes, that error is because the build for swan did not have the big endian flag but wrf did. however, because wrf was built first then swan, it can cause a conflict.  all the builds need to have the same flags (this problem strangely does not occur on all systems, but for yours it does).
so please make those changes to the compiler file, and then rebuild.

let me know if that works.
-j



John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
jcwarner@usgs.gov<mailto:jcwarner@usgs.gov>

https://www.usgs.gov/staff-profiles/john-warner


________________________________

**Comment by mf99274** [comment]
Hi John, 

You are totally right. I was running in the DEBUG mode which doesn't set the  **FFLAGS**  so when I turned that off it worked. Now I am getting the following:

**MCT::m_SparseMatrixPlus::initFromRoot_:: FATAL--length of vector y different from row count of sMat.Length of y =    57404 Number of rows in sMat =    56925**  

I am using SCRIP from the old version to create the weights, I will try to update it and see if I get anything different. I will close this comment and open a new one if I need more help about the error above. 

Thank you a lot for the help and patience, 
Matheus
