### ISSUE TITLE
No model output and netcdf.inc error

### ISSUE THREAD

**Issue by clairs256** [DOI-USGS/COAWST#20]
Hi,

I had compiled COAWST and got the coawstM file but when I tried running the model there was no output (that I could find). So I started the process again and again got the coawstM file but this time noticed the error in the build log:

 Error : Not found /apps/netcdf/4.7.3/include/netcdf.inc
        Please check this installation of NetCDF and re-run this configure script

Before I try running the model again to see if there's an output, should I investigate this error first? I'm using the NCI supplied libraries for netcdf etc. Netcdf library starts at version 4.6.3 and the netcdf.inc file is in the /apps/netcdf/4.7.3/include/Intel folder

Thanks,
Clair

**Comment by jcwarner-usgs** [comment]
this is a bit strange. The model would not compile without netcdf.inc.  so i am not sure how you got a coawstM.  
what case are you running?  suggest you start out with a test case that we distribute, maybe just roms for now. you can post the build log here and i can see if it made a coawstM.

**Comment by clairs256** [comment]
I'm trying the Sandy case. I've just tried a fresh build in case I somehow got a coawstM from somewhere else and that also produced a coawstM

Here's the previous build log:
[coawstNewBuild2Jan.log](https://github.com/jcwarner-usgs/COAWST/files/5799754/coawstNewBuild2Jan.log)

Thanks

**Comment by jcwarner-usgs** [comment]
not sure why the first one worked, but it looks like there was no MCT calls in there.
the second one failed with errors like
cean_coupler.f90(18): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [M_MCTWORLD]
      USE m_MCTWorld, ONLY : MCTWorld_init => init
----------^
and that means it can not find MCT.
So you need to compile MCT somewhere, and then set MCT_INCDIR and MCT_LIBDIR.  
let me know how it goes.

**Comment by clairs256** [comment]
I forgot the 'make install' for MCT in the second attempt. Once corrected it also produced a coawstM file but also has the netcdf.inc error:
[coawstBuild12Jan_v3.log](https://github.com/jcwarner-usgs/COAWST/files/5804523/coawstBuild12Jan_v3.log)

**Comment by jcwarner-usgs** [comment]
not sure.  WRF could not find netcdf.inc, so it could not make all the libs (libio_netcdf.a i think had a problem).
if you do
ls -ltr
and you see coawstM at the bottom, then it made an executable .  give it a try.

**Comment by clairs256** [comment]
Yep coawstM appears at the bottom

Could the no output when trying to run the model be unrelated to netcdf.inc issue? I kept trying with the first coawstM to try to learn how to run the model. After much trial and error I managed to get some error files. The latest is:
[cwstv3.e15461283.txt](https://github.com/jcwarner-usgs/COAWST/files/5805150/cwstv3.e15461283.txt)

But I had problems defining NP for the mpirun so I just set -np 3. I had help from the NCI team for the settings in this run script 
[run_COAWST.sh.txt](https://github.com/jcwarner-usgs/COAWST/files/5805162/run_COAWST.sh.txt)

I'm happy to keep exploring/learning these errors myself but I'm just not sure if I'm heading down a rabbit hole if the netcdf.inc error is an underlying problem

**Comment by jcwarner-usgs** [comment]
a lot of this is in the user manual.
when you run the job you are pointing to the coupling.in
the coupling.in lists the number of procs for the atm, for the ocean, and for the wav.
then you need to go into each model input file and set that accordingly.
-for roms, the ocean.in sets NtileI and NtileJ, and so you want NtileI * NtileJ to = # procs set for ocean in coupling.in
 -for wrf, you set nprocs_x and nprocs_y in the namelist.inp, etc.
- for swan, you dont have to set the tiling in the swan.in

the error you are getting makes me think that you did not copy the namelist.input, and the wrf* files to the root location where coawstM is.  try that.

also i think i see why you are having netcdf problems with WRF.

you set for roms:
export NETCDF_LIBDIR=/apps/netcdf/4.7.3/lib/Intel
export NETCDF_INCDIR=/apps/netcdf/4.7.3/include/Intel

and for WRF
export NETCDF=/apps/netcdf/4.7.3
then WRF thinks that the include stuff is in /apps/netcdf/4.7.3/include
and the libs are in /apps/netcdf/4.7.3/lib
but that is not where they are.  your paths are a little weird. 
can you ask your IT to help you set up a soft link so that
ln -s /apps/netcdf/4.7.3/lib/ /apps/netcdf/4.7.3/lib/Intel
ln -s /apps/netcdf/4.7.3/include/ /apps/netcdf/4.7.3/lib/include
that might work.  do you see what i am doing there?

you should recompile so wrf can find the netcdf.inc file.

-j

**Comment by clairs256** [comment]
Success :) Model is running and I'm getting wrfout files. As a quick fix I changed the netcdf.inc path in WRF configure to include the extra Intel folder. No netcdf.inc error in the recompile. If I encounter other problems with it I'll contact IT. 
Thanks for your help!

**Comment by jcwarner-usgs** [comment]
NICE !!!
