### ISSUE TITLE
Error when installing SCRIP_COAWST

### ISSUE THREAD

**Issue by jameshlywiak** [DOI-USGS/COAWST#3]
Hello,

When attempting to install SCRIP_COAWST, I receive this error:

./remap_write.f(337): error #6404: This name does not have a type, and must have an explicit type.   [NF_NETCDF4]
       ncstat = nf_create (output_ncfile, NF_NETCDF4, nc_file_id)
------------------------------------------^

I have netcdf v4.2.1.1 installed, I'm compiling using ifort, and my makefile reads:

USE_MPI=on               # distributed-memory parallelism
USE_MPIF90=on            # compile with mpif90 script
USE_NETCDF4=on

If anyone out there knows how to deal with this error, I would greatly appreciate the help.

Cheers,
James

**Comment by jcwarner-usgs** [comment]
sorry i did not get back to you on this, but probably better on github here. The issue is not in the scrip build, but instead for the install of netcdf.  We need netcdf4 capabilities of 'groups.' So just using netcdf4.x is not enough,  in addition when the netcdf was installed, did they use
--enable-netcdf-4
so please check you netcdf install by typing 
 nf-config --has-nc4
and you need to get a  'yes' response.
